### ISSUE TITLE
warlock voidwalker disappears when sacraficed

### ISSUE THREAD

**Issue by oldspices** [RetroWoW/RetroWoW#137]
**Description**:
when you press sacrafice, it does not work as in no shield given, andyou lose pet
**Current behavior**: Tell us what happens
i ithink it only happens when VW is out of LoS
**Expected behavior**: Tell us what should happen instead
it should either sacrafice correctly or not sacrafice at all thus keeping pet alive
**Steps to reproduce the problem**:

1. have pet stand los 
2. sac
3. plzfix

**Source:**

**Comment by modnaros** [comment]
Confirmed. 
If you line of sight your voidwalker, sacrifice buff will not apply. I'm not positive as to whether or not this is intended, however. 
I'd try to find some evidence of players managing to do this on video, because no other pet spell works through LoS, Im not sure if sacrifice is meant to be an exception or not.

**Comment by xiaoxoxo** [comment]
using sacrifice(sheild) should work same way, currently it will dismiss pet but give no sheild if used while LoS.
