### ISSUE TITLE
Gnomish Death Ray :(

### ISSUE THREAD

**Issue by Hotbeef750** [RetroWoW/RetroWoW#164]
**Description**: Gnomish Death Ray this nice old school trinket did a lot more damage then its doing atm on the server :( can you please buff it a bit? it was stronger back in the days on retail, please i love that trinket >.<

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Hotbeef750** [comment]
:c

**Comment by Hotbeef750** [comment]
u will not fixx it? or at least try it?

**Comment by modnaros** [comment]
I mean if you made a legitimate report citing sources whether video or text to show the current algorithm is busted, they'd pay attention to it, but all you've said is "Damage is lower than it should be" but you don't provide any evidence to the contrary.

**Comment by Hotbeef750** [comment]
i said whats wrong with it and that should be enough mr. sherlock. not my fault if they dont do anything

**Comment by modnaros** [comment]
What exactly have you said that's wrong with it? You've said you THINK the damage is too low, but you can't PROVE the damage is too low, thus they won't change it because you can't PROVE it. 

Please, in future, follow the proper guidelines for posting bug reports, otherwise they will just be ignored as this one.

**Comment by Hotbeef750** [comment]
hahaha get a life xDD understand it sherlock junior lul
