### ISSUE TITLE
3fken weeks waiting for GM response??

### ISSUE THREAD

**Issue by donor123** [RetroWoW/RetroWoW#210]
Use Discord not Github

**Comment by mentos987** [comment]
Did you try deleting wbd folder?

**Comment by mentos987** [comment]
When it comes to buffs they generally don't stack with other buffs with the same spell icon, which is the case with Atiesh and boomkin aura. And I don't think the Druid Atiesh even gives any spellpower so this is probably blizzlike.

Arena has been reworked on this server. No trinket here. The next best thing you can get is the burrowers shell from aq40.

I haven't seen your felhunter bug tho, I have no clue how to solve it.

If you bought a spellpower Atiesh for a druid then I suggest you make a request for a refund or to move it to another character, since you didn't seem to know that they don't stack.

**Comment by donor123** [comment]
But ossirian helped me get the trinket on my other toon, it just so happened I collected it now on other toons and need it done there too... can we do that ? 


As far as the Atiesh, yeah I guess I’ll just transfer it.. :( 

Or can I just get the credit changed to DP? 

I don’t need a refund I want to support the server.

**Comment by donor123** [comment]
Okay can I get a ingame msg for the atiesh staff to change character or what’s the process

**Comment by donor123** [comment]
Hello, ossirian helped me with the quest issue. 

Can you please refund atiesh off Ralphtauren into donor points! 

I still want to support your server <3

Thank you!

**Comment by donor123** [comment]
Hey Kelzo!

What’s the next step man?
