### ISSUE TITLE
Cross faction nameplates

### ISSUE THREAD

**Issue by Soviethammer** [RetroWoW/RetroWoW#79]
**Description**: if you stand in hyjal and next to another faction their nameplate will show up eventhough you have it turned off

**Current behaviour**: shows friendly nameplates on everyone that is your opposite faction when not at a pvp zone

**Expected behaviour**: Should not show nameplates if turned off in interface

**Steps to reproduce the problem**: 

1. Go to hyjal
2. Stand next to another faction member
3. Get annoying nameplates

**Source:**

**Comment by Bam27** [comment]
This is a **client side issue**. It can be fixed by writing an addon for it, but there hasn't been any that I could find yet. 
Unfortunately, in order to fix this kind of issue, it would require every player to download a patch and apply it to their game (something that we have no plans of implementing.)

Closing this. 

I suggest that you bind the option to show all name plates, instead of only enemies.
